"use client";

import { useEffect, useMemo, useState } from "react";
import { contentVersion, findItemById, items, rarities, searchItems, type ItemRecord, type Rarity } from "@/src/lib/itemRepository";
import { defaultRunState, loadRunState, saveRunState, setItemCount, type RunStateV1 } from "@/src/lib/runState";

type Tab = "items" | "saved" | "build" | "reference";
const tabs: { id: Tab; icon: string; label: string }[] = [{ id: "items", icon: "▦", label: "Items" }, { id: "saved", icon: "★", label: "Saved" }, { id: "build", icon: "⌁", label: "Build" }, { id: "reference", icon: "▥", label: "Reference" }];
const referenceTools = ["Proc chains", "Stack types", "Equipment", "Survivor builds"];

export default function Home() {
  const [tab, setTab] = useState<Tab>("items"); const [query, setQuery] = useState(""); const [rarity, setRarity] = useState<Rarity | "All">("All"); const [scope, setScope] = useState<"all" | "base" | "expansion">("all");
  const [run, setRun] = useState<RunStateV1>(defaultRunState); const [hydrated, setHydrated] = useState(false); const [undo, setUndo] = useState<RunStateV1 | null>(null); const [reference, setReference] = useState("Proc chains"); const [online, setOnline] = useState(true); const [installPrompt, setInstallPrompt] = useState<{ prompt: () => Promise<void>; userChoice: Promise<unknown> } | null>(null);
  useEffect(() => {
    // This external device-local store is deliberately hydrated after SSR.
    queueMicrotask(() => { setRun(loadRunState()); setHydrated(true); setOnline(navigator.onLine); });
    const update = () => setOnline(navigator.onLine);
    const captureInstall = (event: Event) => { event.preventDefault(); setInstallPrompt(event as Event & { prompt: () => Promise<void>; userChoice: Promise<unknown> }); };
    addEventListener("online", update); addEventListener("offline", update);
    addEventListener("beforeinstallprompt", captureInstall);
    if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => undefined);
    return () => { removeEventListener("online", update); removeEventListener("offline", update); removeEventListener("beforeinstallprompt", captureInstall); };
  }, []);
  useEffect(() => { if (hydrated) saveRunState(run); }, [run, hydrated]);
  const visible = useMemo(() => { const found = searchItems(query, rarity, scope); return tab === "saved" ? found.filter((item) => run.savedItemIds.includes(item.id)) : found; }, [query, rarity, scope, tab, run.savedItemIds]);
  const stacks = Object.values(run.items).reduce((total, count) => total + count, 0);
  function mutate(next: RunStateV1) { setUndo(run); setRun(next); }
  function toggleSaved(id: string) { mutate({ ...run, savedItemIds: run.savedItemIds.includes(id) ? run.savedItemIds.filter((entry) => entry !== id) : [...run.savedItemIds, id] }); }
  function changeCount(id: string, amount: number) { mutate(setItemCount(run, id, (run.items[id] ?? 0) + amount)); }
  function toggleChecklist(id: string) { mutate({ ...run, checklistItemIds: run.checklistItemIds.includes(id) ? run.checklistItemIds.filter((entry) => entry !== id) : [...run.checklistItemIds, id] }); }
  return <main className="app-shell"><header className="app-header"><div className="identity"><img src="/assets/storm-atlas-icon.png" alt="" width="42" height="42"/><div><h1>Storm Atlas</h1><p>Offline run companion</p></div></div><div className="header-status"><i /> {online ? "LOCAL DATA" : "OFFLINE"} <strong>{contentVersion}</strong>{installPrompt && <button className="install-button" onClick={async () => { await installPrompt.prompt(); setInstallPrompt(null); }}>Install</button>}</div></header><section className="workspace"><aside className="side-nav" aria-label="Primary navigation"><div className="nav-label">Run tools</div>{tabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}><span>{item.icon}</span>{item.label}{item.id === "saved" && run.savedItemIds.length ? <b>{run.savedItemIds.length}</b> : null}{item.id === "build" && stacks ? <b>{stacks}</b> : null}</button>)}<div className="side-note"><span>OFFLINE READY</span><p>Catalog v{contentVersion}. Your active run stays on this device.</p></div></aside><section className="content">{(tab === "items" || tab === "saved") && <Catalog tab={tab} visible={visible} query={query} setQuery={setQuery} rarity={rarity} setRarity={setRarity} scope={scope} setScope={setScope} saved={run.savedItemIds} toggleSaved={toggleSaved} changeCount={changeCount} stacks={stacks} openBuild={() => setTab("build")} />}{tab === "build" && <Build run={run} changeCount={changeCount} undo={undo} onUndo={() => { if (undo) { setRun(undo); setUndo(null); } }} reset={() => mutate({ ...defaultRunState, items: {}, savedItemIds: [], checklistItemIds: [] })} toggleChecklist={toggleChecklist} />}{tab === "reference" && <Reference reference={reference} setReference={setReference} addToBuild={(id) => changeCount(id, 1)} />}</section></section><nav className="bottom-tabs" aria-label="Mobile navigation">{tabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav></main>;
}

function Catalog({ tab, visible, query, setQuery, rarity, setRarity, scope, setScope, saved, toggleSaved, changeCount, stacks, openBuild }: { tab: Tab; visible: ItemRecord[]; query: string; setQuery: (v: string) => void; rarity: Rarity | "All"; setRarity: (v: Rarity | "All") => void; scope: "all" | "base" | "expansion"; setScope: (v: "all" | "base" | "expansion") => void; saved: string[]; toggleSaved: (id: string) => void; changeCount: (id: string, n: number) => void; stacks: number; openBuild: () => void }) {
  return <><div className="screen-heading"><div><span>CATALOG / {tab.toUpperCase()}</span><h2>{tab === "saved" ? "Saved items" : "Item catalog"}</h2><p>Search the bundled, versioned content—no connection required.</p></div><div className="count-badge">{visible.length}</div></div><div className="controls"><label className="search"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search names, aliases, effects, or tags"/>{query && <button onClick={() => setQuery("")}>×</button>}</label><div className="rarities">{(["All", ...rarities] as const).map((name) => <button key={name} data-rarity={name} className={rarity === name ? "active" : ""} onClick={() => setRarity(name)}>{name}</button>)}</div><div className="segmented"><button className={scope === "all" ? "active" : ""} onClick={() => setScope("all")}>All content</button><button className={scope === "base" ? "active" : ""} onClick={() => setScope("base")}>Base Game</button><button className={scope === "expansion" ? "active" : ""} onClick={() => setScope("expansion")}>Expansions</button></div></div><div className="summary"><div><strong>{items.length}</strong><span>ITEMS</span></div><div><strong>{rarities.length}</strong><span>RARITIES</span></div><div><strong>{new Set(items.flatMap((item) => item.categories)).size}</strong><span>TAGS</span></div><button onClick={openBuild}><span><b>Active build</b><small>{stacks} stacks tracked</small></span><strong>Review →</strong></button></div><div className="item-grid">{visible.map((item) => <ItemCard key={item.id} item={item} saved={saved.includes(item.id)} toggleSaved={toggleSaved} add={() => changeCount(item.id, 1)} />)}{!visible.length && <div className="empty"><span>⌕</span><h3>No items found</h3><p>Try an alias, rarity, or content scope.</p></div>}</div></>;
}
function ItemCard({ item, saved, toggleSaved, add }: { item: ItemRecord; saved: boolean; toggleSaved: (id: string) => void; add: () => void }) { return <article className="item-card" data-rarity={item.rarity}><div className="rarity-strip"/><button className={saved ? "save saved" : "save"} aria-label={`Save ${item.name}`} onClick={() => toggleSaved(item.id)}>★</button><div className="item-icon"><img src={item.iconPath} alt=""/></div><div className="item-copy"><div className="card-title"><h3>{item.name}</h3><span>{item.rarity}</span></div><p>{item.effect}</p><div className="tags">{item.categories.map((tag) => <span key={tag}>{tag}</span>)}<span className={`status ${item.sourceStatus}`}>{item.sourceStatus}</span></div><div className="item-meta">{item.scope} · <b className={`priority ${item.priority}`}>{item.priority}</b></div><button className="add-button" onClick={add}>＋ Add to build</button></div></article>; }
function Build({ run, changeCount, undo, onUndo, reset, toggleChecklist }: { run: RunStateV1; changeCount: (id: string, amount: number) => void; undo: RunStateV1 | null; onUndo: () => void; reset: () => void; toggleChecklist: (id: string) => void }) { const entries = Object.entries(run.items).map(([id, count]) => ({ item: findItemById(id), count })).filter((entry): entry is { item: ItemRecord; count: number } => !!entry.item); const stacks = entries.reduce((n, entry) => n + entry.count, 0); const present = new Set(entries.flatMap(({ item }) => item.categories)); const gaps = ["Mobility", "Defense", "Healing", "Proc"].filter((tag) => !present.has(tag)); const picks = items.filter((item) => item.priority === "core" && !run.checklistItemIds.includes(item.id)).slice(0, 3); return <><div className="screen-heading"><div><span>RUN / BUILD</span><h2>Active build</h2><p>Track stacks by item ID. Fill the gaps before chasing excess damage.</p></div><div className="action-row">{undo && <button className="clear-build" onClick={onUndo}>Undo</button>}<button className="clear-build" onClick={reset}>Reset run</button></div></div><div className="build-stats"><div><span>TOTAL STACKS</span><strong>{stacks}</strong></div><div><span>UNIQUE ITEMS</span><strong>{entries.length}</strong></div><div><span>GAPS</span><strong className="ready">{gaps.length ? gaps.join(", ") : "COVERED"}</strong></div></div><section className="build-panel"><div className="panel-heading"><div><span>TRACKED ITEMS</span><h3>Your current run</h3></div><b>{entries.length}</b></div>{entries.length ? entries.map(({ item, count }) => <div className="build-item" key={item.id}><img src={item.iconPath} alt=""/><div><strong>{item.name}</strong><span>{item.priority.toUpperCase()} · {item.priorityReason}</span>{item.stackFormula && <small>{item.stackFormula.replace("stacks", String(count))}</small>}</div><div className="stepper"><button aria-label={`Remove ${item.name}`} onClick={() => changeCount(item.id, -1)}>−</button><b>{count}</b><button aria-label={`Add ${item.name}`} onClick={() => changeCount(item.id, 1)}>＋</button></div></div>) : <div className="empty"><span>⌁</span><h3>No items tracked</h3><p>Add drops from the catalog as they appear.</p></div>}</section><section className="decision-panel"><span>NEXT PICKUP CHECK</span><h3>Prioritize what fixes the run.</h3>{gaps.length ? <p>Current gaps: {gaps.join(", ")}. Address these before taking narrow upgrades.</p> : <p>Coverage is balanced. Choose items that reinforce your survivor’s strongest proc or damage loop.</p>}{picks.map((item) => <label className="check-row" key={item.id}><input type="checkbox" checked={run.checklistItemIds.includes(item.id)} onChange={() => toggleChecklist(item.id)}/><span><b>{item.name}</b> — {item.priorityReason}</span></label>)}</section></>; }
function Reference({ reference, setReference, addToBuild }: { reference: string; setReference: (value: string) => void; addToBuild: (id: string) => void }) { const related = reference === "Proc chains" ? items.filter((item) => item.categories.includes("Proc")) : reference === "Stack types" ? items.filter((item) => item.stackFormula) : reference === "Equipment" ? items.filter((item) => item.categories.includes("Utility")) : items.filter((item) => item.priority === "core"); return <><div className="screen-heading"><div><span>FIELD / REFERENCE</span><h2>Reference</h2><p>Short answers tied directly to your local item catalog.</p></div></div><div className="reference-grid">{referenceTools.map((name) => <button className={name === reference ? "active-reference" : ""} key={name} onClick={() => setReference(name)}><i>{name === "Proc chains" ? "⚙" : name === "Stack types" ? "×" : name === "Equipment" ? "⌁" : "◎"}</i><div><h3>{name}</h3><p>{name === "Proc chains" ? "Chance effects and chain reactions" : name === "Stack types" ? "What scales per copy" : name === "Equipment" ? "Utility and active-run choices" : "Survivor-aware core priorities"}</p></div><span>›</span></button>)}</div><section className="build-panel reference-detail"><div className="panel-heading"><div><span>WORKING GUIDE</span><h3>{reference}</h3></div></div><p>{reference === "Proc chains" ? "Proc items reward consistent hits. Start with reliable hit rate, then add missiles and chain clear." : reference === "Stack types" ? "Only published formulas are shown. Treat unlisted effects as descriptive until separately reconciled." : reference === "Equipment" ? "Use utility choices to solve the immediate fight or route problem, not as a substitute for core movement and survival." : "Use core labels as a baseline, then favor what matches your survivor’s hit pattern and current gaps."}</p>{related.map((item) => <div className="guide-item" key={item.id}><img src={item.iconPath} alt=""/><div><b>{item.name}</b><small>{item.stackFormula ?? item.priorityReason}</small></div><button className="add-button" onClick={() => addToBuild(item.id)}>Add</button></div>)}</section></>; }
